### ISSUE TITLE
500 Received after revoking OAuth Access

### ISSUE THREAD

**Issue by jro619** [hoyley/spot-on#1]
Empty page with "Internal Server Error" shown in the app after revoking OAuth access to the app within Spotify.

Steps to reproduce:
- Authenticate with app
- Log into Spotify web
- Go to Apps
- Revoke access to SpotOn
- Go back to app
- Note that app is broken with 500 received

Please fix!

#first

**Comment by hoyley** [comment]
This issue is resolved. There is now a "status" field on the spotify_users table. When auth tokens are revoked, the status is changed to revoked. Users with revoked status are still visible, but no Spotify API calls will be attempted.
